using PlayFab.Internal;
using PlayFab.MultiplayerModels;

namespace Plugin.PlayFab;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
public class RequestPartyResponse : PlayFabResultCommon
{
    /// <summary>
    /// The connected players in the party.
    /// </summary>
    public List<ConnectedPlayer> ConnectedPlayers;

    /// <summary>
    /// The fully qualified domain name of the virtual machine that is hosting this party session.
    /// </summary>
    public string FQDN;

    /// <summary>
    /// The IPv4 address of the virtual machine that is hosting this party session.
    /// </summary>
    public string IPV4Address;

    /// <summary>
    /// The time (UTC) at which a change in the party state was observed.
    /// </summary>
    public DateTime? LastStateTransitionTime;

    /// <summary>
    /// The guid string party ID of the party session.
    /// </summary>
    public string PartyId;

    /// <summary>
    /// The ports the party session uses.
    /// </summary>
    public List<Port> Ports;

    /// <summary>
    /// The region the party session is located in.
    /// </summary>
    public AzureRegion? Region;

    /// <summary>
    /// The string server ID of the party session generated by PlayFab.
    /// </summary>
    public string ServerId;

    /// <summary>
    /// The state of the party session.
    /// </summary>
    public string State;

    /// <summary>
    /// The virtual machine ID that the party session is located on.
    /// </summary>
    public string VmId;
}
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.